### ISSUE TITLE
Interface differences

### ISSUE THREAD

**Issue by davesidious** [jameswlane/jest-express#108]
- `jest-express` version: 1.8.0
- `node` version: 8.11.2
- `yarn` version: 1.10.1

It appears the `Response()` interface differs from that offered by express's implementation.  Namely the `status()` call only returns the methods listed in the example on [express's documentation page](https://expressjs.com/en/4x/api.html#res.status) and not the Response object itself (as per express's [codebase](https://github.com/expressjs/express/blob/master/lib/response.js#L66)).  There might be others, but this one has me blocked, so I've not noticed.

Are there plans to fix this?

**Comment by jameswlane** [comment]
I can work on getting a fix out in the next couple days.

If you would want to PR’s are welcome and if you can knock it out sooner I will merge it in and cut a new release.

**Comment by davesidious** [comment]
I'd absolutely _love_ to do it but I will be away from my PC until next Monday.  If you want to wait until then, I can get a PR together early next week.

Thanks for the prompt reply!

**Comment by jameswlane** [comment]
Thanks to @dozenne this should be fixed via this [PR](https://github.com/jameswlane/jest-express/pull/115)
