### ISSUE TITLE
Chaining of res.status().json() not supported

### ISSUE THREAD

**Issue by cvburgess** [jameswlane/jest-express#114]
- `jest-express` version: 23.6.0
- `node` version: 10.6.0
- `npm` (or `yarn`) version: 6.1.0

Relevant code or config

```javascript
const req = new Request();
await myMiddleware(req, res);
const res = new Response();
expect(res.json).toBeCalled();


// in myMiddleware
return res.status(status).json(data);
```

What you did:

When chaining status and json to gether, the mock for `.toBeCalled` does not work on the second chained function.

What happened:

```
    expect(jest.fn()).toBeCalled()

    Expected mock function to have been called, but it was not called.

      61 | 
      62 |     expect(res.status).toBeCalledWith(200);
    > 63 |     expect(res.json).toBeCalled();
         |                      ^
      64 |   });
      65 | 

      at Object.toBeCalled (utils/_tests_/middleware.test.js:63:22)
```

Reproduction repository:

Problem description:

If i change my code to unchain the `res`, the mocks were correctly.

If i leave them chained, it fails.

Suggested solution:

Allow for chaining or mention that it is not supported in the docs.

**Comment by jameswlane** [comment]
@cvburgess I won't be able to try and tackle this for about a week or so. I have been working on a new release for another library I have.

PRs are welcome if you would like to try and resolve this issue and PR it back to master.

If not I will try and get to it next week sometime.

**Comment by cvburgess** [comment]
@jameswlane I will give it a shot but i am quite busy myself.

I will leave a comment here if I make any progress :)

**Comment by jameswlane** [comment]
Someone added a PR last night that should resolve your issue and another pending issue. I just need to review it, pull it in and cut a new release.

**Comment by jameswlane** [comment]
Thanks to @dozenne this should be fixed via this [PR](https://github.com/jameswlane/jest-express/pull/115)
