### ISSUE TITLE
Support `req.app` and get and set methods on the request object.

### ISSUE THREAD

**Issue by sidhuko** [jameswlane/jest-express#183]
**Is your feature request related to a problem? Please describe.**
I have test failures when following supported API methods in express.

**Describe the solution you'd like**
When setting a singleton to be available throughout the express application:
```app.set('logger', console)```
I should be able to request them from within a route using the following:
```req.app.get('logger')```

**Describe alternatives you've considered**
I've been able to mock `req.app` to contain an Express mock on individual routes but for test against the whole server where jest automatic mocks are used I receive runtime errors:
```TypeError: Cannot read property 'get' of undefined```

**Comment by jameswlane** [comment]
@sidhuko PR's are welcome if you would like to try and resolve this issue and PR it back to master it would be greatly appreciated.

If I will do my best to try and get to it this weekend.

**Comment by sidhuko** [comment]
@jameswlane No problems, was a simple fix, PR is waiting. You might want to downstream as a patch if it causes the TypeError. I didn't commit a version but can if you let me know patch or minor.

Thanks!
