### ISSUE TITLE
TypeError: res.removeHeader is not a function

### ISSUE THREAD

**Issue by benbakhar** [jameswlane/jest-express#392]
**Describe the bug**
Hi, i'm using the `helmet` package in my express app and as part of it's default middleware configurations it is [removing ](https://github.com/helmetjs/hide-powered-by/blob/master/index.ts#L17)the `X-Powered-By` header using `response.removeHeader` method. Apparently this method is missing in the `Response` class.

Would love to submit a PR if that makes sense to you.

**Expected behavior**
Should mock this method within the `Response` class;

**Screenshots**
![removeHeader](https://user-images.githubusercontent.com/7517258/72509928-315e6e00-3851-11ea-8f0e-7b43b7f070af.PNG)

- express version: 4.17.1
- jest-express version: 1.10.1
- node version: 12.14.0
- npm version: 6.13.4

**Comment by jameswlane** [comment]
@benbakhar PR's are welcome, I would appreciate if you can get that knocked out and I can merge it in a cut a release ASAP

**Comment by benbakhar** [comment]
sure thing! will hit you with a PR soon.
