### ISSUE TITLE
request.setHeaders() lowercases the header name, but request.get() does not

### ISSUE THREAD

**Issue by tamias** [jameswlane/jest-express#414]
**Describe the bug**
`request.setHeaders(header, value)` calls `.toLowerCase()` on the header before storing it, but `request.get(header)` does not call `.toLowerCase()` on the header before looking up the value.

**To Reproduce**
1. Create a `Request` object: `const req = new Request();`
2. Set a header: `req.setHeaders('Referer', 'https://www.example.com');`
3. Get the header: `req.get('Referer');`

**Expected behavior**
`req.get('Referer')` should return `'https://www.example.com'`; instead it returns `undefined`.

**Comment by jameswlane** [comment]
@tamias , If you would like to PR a fix for this I would be more then happy to merge it in.

**Comment by tamias** [comment]
@jameswlane I'm coming back to this now, but I wanted to clean up some linting errors in the tests first: https://github.com/jameswlane/jest-express/pull/425

**Comment by jameswlane** [comment]
@tamias Awesome 👍 I look forward to that.

**Comment by y0y0z** [comment]
@jameswlane: would you like to close this issue?

**Comment by tamias** [comment]
It's been a busy couple weeks.  I missed my chance to fix the issue, but I've added tests. :)
