### ISSUE TITLE
ability to access the response body

### ISSUE THREAD

**Issue by y0y0z** [jameswlane/jest-express#428]
when the response body needs to be tested, jest-express is missing the feature of accessing the response body directly. for instance, assuming a json response; then one would like to test the response body structure, keys, values, etc.

for instance, this is what i would expect:

```javascript
// foo.test.js
const { Response } = require("jest-express");
const foo = require("./foo");

describe('foo', () => {
  const resMock = new Response();
  const res = foo(resMock);
  expect(res.body.uptime).toBeGreaterThan(0);
});

// foo.js
module.exports = res => {
  res.type("json").send({uptime: process.uptime()})
  return res;
}
```

using `expect(response.send).toBeCalledWith([body])` does not cover the testing case above since the body is constructed within the callee and the caller has no notion of it. the caller only accept the response back from the callee and then test it.

also tried to leverage the `on('data')` for the mocked response, but it was no good:
```javascript
describe('foo', () => {
  const resMock = new Response();
  const res = foo(resMock);
  let body = [];
  res.on("data", chunk => {
      body.push(chunk);
  }).on("end", () => {
    body = body.join('');
    console.log(body);
  });
});
```
but the `res` object, has no `on()`
> TypeError: res.on is not a function

making the mocked reponse (`resMock`) have a `body` property, that is `resMock.body`, that returns the reponse body should be enough.

**Comment by jameswlane** [comment]
@y0y0z that sounds reasonable, I would be more then happy to merge a PR adding this into the lib.

**Comment by y0y0z** [comment]
@jameswlane: when a new version will be released?

**Comment by jameswlane** [comment]
@y0y0z it looks like [semantic-release](https://github.com/semantic-release/semantic-release) did not cut a new release. When I get home today I will check the pipelines and manually cut a new release or make a dummy commit to cut a release.

**Comment by y0y0z** [comment]
@jameswlane: kindly release a new version
