### ISSUE TITLE
Router.route('/foo').put() doesn't exist.

### ISSUE THREAD

**Issue by jasonseminara** [jameswlane/jest-express#66]
- `react` version: n/a
- `node` version: 10.7.0
- `npm` (or `yarn`) version: 6.2.0

Relevant code or config

> In lib/router.js, only route.get is defined.

What you did:
```javascript
const express  = require('jest-express');
const router = express.Router();
const dummy = (req, res) => res.send('blurg');

// these 'verb' functions must be chainable to work properly 
router.route('/:id')
  .get(dummy)
  .put(dummy)
  .delete(dummy);

module.exports = router;
```

What happened:

Reproduction repository:

Problem description:

Suggested solution:

**Comment by jameswlane** [comment]
@jasonseminara, thank you for submitting an issue. I am at Node Summit 2018 this week. If you would like to submit a PR adding this functionality, it would be greatly appreciated. If not I will try and get a fix for this resolve in between sessions.

**Comment by jasonseminara** [comment]
Awesome! I just updated my code locally to finish my project. I'll convert to ts and create a PR
