### ISSUE TITLE
Update CONTRIBUTING.md

### ISSUE THREAD

**Issue by sheerun** [jameswlane/jest-express#92]
It's nice there's contributing.md file, but it's not nice it's not up to date. For example:

```
npm start validate
```

returns 

npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sheerun/.npm/_logs/2018-09-17T17_09_51_234Z-debug.log

Could you please fix this file or remove it?

**Comment by jameswlane** [comment]
This was a copy paste from another project, It should be updated.
